CREATE TABLE post(
Id SMALLINT(5) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(30) NOT NULL,
Email VARCHAR(70) NOT NULL UNIQUE,
Mobile CHAR(10) NOT NULL UNIQUE,
Pword CHAR(32) NOT NULL,
Salary FLOAT(7,2) NOT NULL,
DOB DATE NOT NULL,
Gender ENUM('Male','Female') DEFAULT 'Male',
Language SET('English','Hindi','Telugu') NOT NULL,
Address TINYTEXT NOT NULL,
Pic VARCHAR(100) NOT NULL,
regOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Status ENUM('InActive','Active') DEFAULT 'InActive'
);